baseURL = "https://ssine.ink/"
title = "Sine's Site"
home = "Home"
languageCode = "zh"
defaultContentLanguage = "zh-cn"

theme = "hugo-coder"

paginate = 50
canonifyurls = true
hasCJKLanguage = true

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = "Sine"
  info = "Computer Science Student"
  description = "Sine's Site"
  keywords = "blog,developer,personal"
  # avatarurl = "images/avatar.jpg"

  favicon_32 = "/favicon.ico"
  favicon_16 = "/favicon.ico"

  hidecredits = true
  hidecopyright = true

  rtl = false

  colorScheme = "auto"

  math = true
  custom_css = ["css/custom.css"]

[languages]

  [languages.en]
    footercontent = "Â© 2016 - 2020 Liu Siyao"
    languagename = "English"
    [languages.en.menu]
    [[languages.en.menu.main]]
      name = "Blog"
      weight = 1
      url = "/posts/"
    [[languages.en.menu.main]]
      name = "Wiki"
      weight = 2
      url = "https://kiwi.ssine.cc"
    [[languages.en.menu.main]]
      name = "Projects"
      weight = 3
      url = "/projects/"

  [languages.zh-cn]
    footercontent = "Â© 2016 - 2020 åˆ˜æ€å°§"
    languagename = "ä¸­æ–‡"
    [[languages.zh-cn.menu.main]]
      name = "åšå®¢"
      weight = 1
      url = "/posts/"
    [[languages.zh-cn.menu.main]]
      name = "ç»´åŸº"
      weight = 2
      url = "https://kiwi.ssine.cc"
    [[languages.zh-cn.menu.main]]
      name = "é¡¹ç›®"
      weight = 3
      url = "/projects/"

  [languages.emoji]
    footercontent = "Â©ï¸ 2ï¸âƒ£0ï¸âƒ£1ï¸âƒ£6ï¸âƒ£ â¡ï¸ 2ï¸âƒ£0ï¸âƒ£1ï¸âƒ£9ï¸âƒ£ ğŸ’"
    languagename = "emoji"
    author = "ğŸ’'s ğŸ•¸ï¸"
    info = "ğŸ’» ğŸ‘¨â€ğŸ“ (ğŸš§, ğŸš«)"
    description = "ğŸ’'s ğŸ•¸ï¸"
    title = "ğŸ’'s ğŸ•¸ï¸"
    [[languages.emoji.menu.main]]
      name = "ğŸ“"
      weight = 1
      url = "/posts/"
    [[languages.emoji.menu.main]]
      name = "ğŸ•¸ï¸"
      weight = 2
      url = "https://kiwi.ssine.cc"
    [[languages.emoji.menu.main]]
      name = "ğŸ†"
      weight = 3
      url = "/projects/"


# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/ssine/"
[[params.social]]
  name = "QQ"
  icon = "fa fa-qq fa-2x"
  weight = 2
  url = "https://wpa.qq.com/msgrd?v=3&uin=963366202&site=qq&menu=yes"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:liu.siyao@qq.com"

